// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mathgeek-lms/mathgeek-backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// CourseRepository is an autogenerated mock type for the CourseRepository type
type CourseRepository struct {
	mock.Mock
}

// CreateCourse provides a mock function with given fields: ctx, request
func (_m *CourseRepository) CreateCourse(ctx context.Context, request model.CreateCourseRequest) (model.Course, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourse")
	}

	var r0 model.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateCourseRequest) (model.Course, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateCourseRequest) model.Course); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(model.Course)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateCourseRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCourseByID provides a mock function with given fields: ctx, id
func (_m *CourseRepository) GetCourseByID(ctx context.Context, id int64) (model.Course, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCourseByID")
	}

	var r0 model.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (model.Course, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) model.Course); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Course)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListCourses provides a mock function with given fields: ctx
func (_m *CourseRepository) GetListCourses(ctx context.Context) ([]model.Course, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetListCourses")
	}

	var r0 []model.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Course, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Course); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCourseRepository creates a new instance of CourseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseRepository {
	mock := &CourseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
