// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mathgeek-lms/mathgeek-backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// LessonRepository is an autogenerated mock type for the LessonRepository type
type LessonRepository struct {
	mock.Mock
}

// CreateLesson provides a mock function with given fields: ctx, request
func (_m *LessonRepository) CreateLesson(ctx context.Context, request model.CreateLessonRequest) (model.Lesson, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateLesson")
	}

	var r0 model.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateLessonRequest) (model.Lesson, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateLessonRequest) model.Lesson); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(model.Lesson)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateLessonRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLessonByID provides a mock function with given fields: ctx, id
func (_m *LessonRepository) GetLessonByID(ctx context.Context, id int64) (model.Lesson, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLessonByID")
	}

	var r0 model.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (model.Lesson, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) model.Lesson); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Lesson)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListLessonsByCourseID provides a mock function with given fields: ctx, courseID
func (_m *LessonRepository) GetListLessonsByCourseID(ctx context.Context, courseID int64) ([]model.Lesson, error) {
	ret := _m.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetListLessonsByCourseID")
	}

	var r0 []model.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.Lesson, error)); ok {
		return rf(ctx, courseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.Lesson); ok {
		r0 = rf(ctx, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLessonRepository creates a new instance of LessonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLessonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LessonRepository {
	mock := &LessonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
